name: Develop build

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check directories
        run: |
          ls .. -r
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -vv
      - name: Archive linux binary
        run: |
          tar czvf ./target/debug/rust-api.tar.gz ./target/debug/rust-api
      - uses: actions/upload-artifact@v2
        with:
          name: api-linux
          path: ./target/debug/rust-api.tar.gz
